### ISSUE TITLE
Zmiany w menu

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-flutter#25]
Prośba o zmianę następujących przycisków:

1 - bez zmian 
2 - do usunięcia skoro będzie to na tabie
3 - bez zmian
4 - przekierowujemy do: https://klubjagiellonski.pl/o-klubie-jagiellonskim/ 
5 - bez zmian
6 - przekierowujemy do: https://www.pola-app.pl/partners 
7 - bez zmian
8 - bez zmian
9 - przekierowujemy do głównej naszego GitHuba: https://github.com/KlubJagiellonski

![menu_flutter](https://user-images.githubusercontent.com/52166969/199004347-c815d322-665b-468f-9a34-eb464da429a3.png)

**Comment by MatPerowicz** [comment]
@rafalgawlik popełniłem błąd w pkt. 6. Nie możemy przekierować na stronę, tylko też zrobić webview.

@AdamWalkowski prośba aby [przerobić to webview tak](https://github.com/KlubJagiellonski/pola-backend/blob/9e905684bb2cf6bdf074224e50d1c58e43740bba/pola/webviews/templates/webviews/partners.html), aby było na nim [dokładnie to, co na tej stronie](https://www.pola-app.pl/partners).

**Comment by MatPerowicz** [comment]
Zmianą nr. 6 zajmie się Kamil

**Comment by rafalgawlik** [comment]
done
