### ISSUE TITLE
Rozmieszczenie ikon 

### ISSUE THREAD

**Issue by WezSieTato** [KlubJagiellonski/pola-flutter#33]
Ikony latarki z ikoną Poli zamieniły się miejscami

| Flutter | iOS |
| - | - |
| ![flutter](https://user-images.githubusercontent.com/4258662/211930618-4b515305-c863-4c60-b33a-5dcdc769d14b.jpeg) | ![ios_native](https://user-images.githubusercontent.com/4258662/211930642-9b5d7772-3ce7-4515-9fac-e2a5340eed4b.jpeg) |

**Comment by MatPerowicz** [comment]
Tak to wyglądało przez cały czas na Androidzie i chyba może tak zostać.

Pytanie o ikonkę ręcznego wpisywania kodu. Może ją jednak przywrócić?

**Comment by WezSieTato** [comment]
Wydaje mi się, że gdzieś pisałeś, żeby ją schować, bo kod można wpisać w wyszukiwarce :D Na iOSie została w sumie przypadkiem, bo zapomniałem o tym.

**Comment by MatPerowicz** [comment]
Zgadza się, ale po gruntownych testach w sklepie uznałem, że chyba lepiej mieć tę ikonkę.

**Comment by WezSieTato** [comment]
Znalazłem jeszcze coś. Tekst z instrukcją ("Umieść kod kreskowy ...") na iosie pojawia się na starcie, ale znika po pierwszym skanowaniu. Co robimy z tym?

**Comment by MatPerowicz** [comment]
Niech znika po pierwszym skanowaniu. Skoro użytkownik już raz zeskanował, to nie potrzebuje instrukcji 🙂

**Comment by MatPerowicz** [comment]
Czy tutaj potrzebne są dodatkowe informacje?

**Comment by WezSieTato** [comment]
Zamykam, w ramach redesignu ten ekran będzie wyglądał jeszcze inaczej.
