### ISSUE TITLE
Nie wczytały się poprawne czcionki na iOS

### ISSUE THREAD

**Issue by WezSieTato** [KlubJagiellonski/pola-flutter#35]
| Flutter | iOS |
| - | - |
| ![flutter](https://user-images.githubusercontent.com/4258662/211930618-4b515305-c863-4c60-b33a-5dcdc769d14b.jpeg) | ![ios_native](https://user-images.githubusercontent.com/4258662/211930642-9b5d7772-3ce7-4515-9fac-e2a5340eed4b.jpeg) |

**Comment by rafalgawlik** [comment]
możwe w ogóle trzeba jakąś libke dodać , która to obsłuży - albo użyć nowej czcionki

**Comment by WezSieTato** [comment]
Wydaje mi się, że problem leży po sposobie w jakie w iOS obsługuje czcionki i wystarczy zadeklarować te czcionki po stronie projektu iOSowego. Będę miał chwilę to zerknę na to.

**Comment by MatPerowicz** [comment]
Czy problem jest rozwiązany?

**Comment by WezSieTato** [comment]
Odpowiednie czcionki zostały dodane na branchu `feature/redesing`
