### ISSUE TITLE
Brak informacji zwrotnej podczas skanowania 

### ISSUE THREAD

**Issue by WezSieTato** [KlubJagiellonski/pola-flutter#36]
W wersji natywnej po zeskanowaniu kodu:
-  telefon wibrował
-  wynik skanowania animował się (nowa karta wysuwała się od dołu)

W wersji flutterowej nowy kafelek po prostu się pojawia.

**Comment by MatPerowicz** [comment]
Tak, zgłaszałem ten błąd już na slacku. Prośba abyś [zerknął do tego wątku] (https://klubjagiellonski.slack.com/archives/C015ZM77X7U/p1672760865661319?thread_ts=1672760865.661319&cid=C015ZM77X7U). Niemniej powinno to działać tak, jak w poprzednich wersjach.

**Comment by MatPerowicz** [comment]
Wydaje się, że problem jest rozwiązany.
