### ISSUE TITLE
Forma wyświetlania wyniku

### ISSUE THREAD

**Issue by WezSieTato** [KlubJagiellonski/pola-flutter#39]
Zeskanowany wynik ma na iOSie formą karty, która jest wyświetlana na tym samym ekranie co skaner. Dzięki temu możliwa jest zmiana taba na inny i powrót do rezultatu.
Na flutterze wynik jest w postaci nowego ekranu, który przykrywa wszystko łącznie z paskiem tabów.

| Flutter | iOS |
| - | - |
| ![IMG_F92651867063-2](https://user-images.githubusercontent.com/4258662/211933178-eadc0c80-d5db-4ea4-bcca-5daf38d94e8d.jpeg) | ![IMG_F92651867063-1](https://user-images.githubusercontent.com/4258662/211933190-453aef38-e528-4fad-b25a-1979186eee67.jpeg) |

**Comment by MatPerowicz** [comment]
Poprzednia wersja jest bardziej przyjazna dla użytkownika, warto do niej wrócić.

I od razu jeśli chodzi o ten ekran:

- warto przywrócić te kolory, które były wcześniej
- należałoby również dodać w tym samym miejscu te przyciski, które mieliśmy dotychczas, a już na pewno przycisk "Zgłoś błąd"

**Comment by MatPerowicz** [comment]
Jednak ekran z opisem firmy, nie powinien przysłaniać tabów.

**Comment by MatPerowicz** [comment]
@WezSieTato czy tutaj potrzeba jeszcze coś wyjaśnić?

**Comment by WezSieTato** [comment]
Zamykam, wszystkie rzeczy zostaną zaadresowane w nowych zadaniach w ramach redesignu
