### ISSUE TITLE
Ekran Menu

### ISSUE THREAD

**Issue by WezSieTato** [KlubJagiellonski/pola-flutter#43]
Ekran menu wygląda zupełnie inaczej niż w natywnej wersji iOS
-  są użyte inne kolory
- inna jest "wielkość" liter
- brakuje opcji "Napisz do nas" i "zgłoś błąd"
- Github zamienił się miejscami z z "oceń Polę"
- "Oceń nas" to teraz "Oceń Polę"
- brakuje informacji o wersji

| Flutter | iOS |
| - | - |
| ![IMG_72788A676C0E-1](https://user-images.githubusercontent.com/4258662/211936367-8f249980-6ada-42ac-b6db-91d8fe98b883.jpeg) | ![IMG_72788A676C0E-2](https://user-images.githubusercontent.com/4258662/211936386-578426a3-2a72-4e8c-9ccf-49bad7c40bdf.jpeg) |

**Comment by MatPerowicz** [comment]
- kolory i czcionka są chyba lepsze niż poprzednie więc możemy je zostawić
- "Napisz do nas" i "Zgłoś Błąd" trzeba koniecznie dodać
- GitHub fabrycznie powinien być na końcu
- "Oceń nas" chyba lepiej brzmi
- informację o wersji należałoby dodać

**Comment by MatPerowicz** [comment]
@WezSieTato Czy potrzebujesz więcej informacji?

**Comment by WezSieTato** [comment]
Ekran ten został zrobiony w ramach redesignu na branchu `feature/redesing`
