### ISSUE TITLE
Błędy w menu

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-flutter#57]
Nie działa przycisk przekierowania na Facebooka. Powinien tam być link: [https://www.facebook.com/app.pola](https://www.facebook.com/app.pola)

Nie działa przycisk „Oceń Polę” ten przycisk miał chyba kierować do sklepu App Store / Google Play. Jak to może wyglądać na flutterze?

**Comment by WezSieTato** [comment]
To ja dołoże, że przycisk Github,m Facebook i Twitter powinien odpalać te strony w przeglądarce (bądź odpowiedniej aplikacji), a nie w web view w Poli.
