### ISSUE TITLE
Ekran firmy: brak informacji o przyjacielu Poli

### ISSUE THREAD

**Issue by WezSieTato** [KlubJagiellonski/pola-flutter#59]
W przypadku zeskanowania firmy, która jest przyjacielem Poli brakuje tej informacji na ekranie firmy i ekranie skanowania.
Na ekranu skanowania powinniśmy dodać serduszko obok nazwy firmy tak jak jest na natywnym iOSie:
![IMG_F92090F4E92B-1 (1)](https://github.com/KlubJagiellonski/pola-flutter/assets/4258662/cf1902dc-50dd-45ef-acb6-ae1e723bbeda)

Za to na ekranie firmy powinno być serduszko z wyjaśnieniem, że jest to PRzyjaciel Poli:
![IMG_E4C63F51CBB0-1 (1)](https://github.com/KlubJagiellonski/pola-flutter/assets/4258662/661aa755-0232-44ba-bca3-13559f7d826a)

**Comment by MatPerowicz** [comment]
Tak warto to dodać

**Comment by WezSieTato** [comment]
Zrobione w ramach redesignu.
